project 'IOSApiProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSApiProject' do
source 'https://github.com/CocoaPods/Specs.git'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSApiProject
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Realm'

end
